### ISSUE TITLE
Selecting text not working

### ISSUE THREAD

**Issue by tscpp** [yuzhenmi/taleweaver#111]
<p align="center">
<h2 align="center">The selection is not working, as shown here</h2>
</p>

![image](https://user-images.githubusercontent.com/47453366/99563842-f88baa00-29c9-11eb-8da9-ef127a51fba9.png)

<p align="center">
<h2 align="center">Here is my setup</h2>
</p>

```typescript
import { doc } from './doc'
import Taleweaver from './.../taleweaver'
import { parse } from './.../util/serialize'

interface EdtiorOptions {
}

export default class Editor implements EdtiorOptions {
   constructor(container: HTMLElement, options: EdtiorOptions) {
      // Apply all keys of options to editor
      for (const key in options) if (Object.prototype.hasOwnProperty.call(options, key))
         this[key] = options[key]

      const _doc = parse(doc, {});
      new Taleweaver(_doc, {}).attach(container)
   }
}
```

<p align="center">
<h2 align="center"> I would very much like to make a pull request.</h2>
</p>

**Comment by tscpp** [comment]
If I scroll down in the document and click somewhere, the caret is way above the line.

**Comment by yuzhenmi** [comment]
This seems like a cache invalidation bug. The caret selections are rendered from positional information in the layout tree, but the text are displayed through the view tree, which is derived from the layout tree. I'm guessing the view tree doesn't have its cache invalidated properly, so it's actually showing outdated text. It could also be a bug in the layout engine though, that is producing invalid states and causing the view tree's cache invalidation to break.

Unfortunately, I am going through another major refactor to improve a bunch of things, mostly focused on the model and render trees but also updates the layout tree implementation quite a bit as collateral damage. I've been doing refactors like this for a while now due to me constantly discovering major design problems (but overall the design is certainly improving) and it certainly poses as a challenge for other contributors. Right now is probably not a good time to make a pull request for this. Hopefully this will be the last major refactor I make, this is the most confident I've felt about the state of things since I started the project!

**Comment by tscpp** [comment]
This also makes the page completely uneditable...

**Comment by tscpp** [comment]
I found the issues.

1. I built the project with parcel (a web bundler) and it didn't work.
2. `* { box-sizing: border-box; }` is **required**

**Comment by yuzhenmi** [comment]
Thanks for identifying the `box-sizing` issue, I'll make sure that's set consistently by the editor.
